CREATE DATABASE SKILLSWAP;
USE SKILLSWAP;

CREATE TABLE STUDENT (
  STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) UNIQUE NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  INSTITUTION VARCHAR(150) NOT NULL,
  COURSE_NAME VARCHAR(150) NOT NULL,
  COURSE_TYPE VARCHAR(20) NOT NULL,
  CITY VARCHAR(100),
  CREDIT_BALANCE DECIMAL(5,2) DEFAULT 0
  );
ALTER TABLE STUDENT
ADD AVAILABILITY VARCHAR(255);
   DESC STUDENT;
   SELECT * FROM STUDENT;
 
 CREATE TABLE SKILL(
   SKILL_ID INT PRIMARY KEY AUTO_INCREMENT,
   SKILL_NAME VARCHAR(100) UNIQUE NOT NULL,
   CATEGORY VARCHAR(100) NOT NULL
   );

  SELECT * FROM SKILL;
  DESC SKILL;
  
CREATE TABLE STUDENT_SKILL (
    STUDENT_ID INT,
    SKILL_ID INT,
    SKILL_TYPE VARCHAR(20) NOT NULL,

    PRIMARY KEY (STUDENT_ID, SKILL_ID, SKILL_TYPE),

    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    FOREIGN KEY (SKILL_ID)
        REFERENCES SKILL(SKILL_ID),

    CHECK (SKILL_TYPE IN ('OFFERED', 'REQUESTED'))
);  

SELECT * FROM STUDENT_SKILL;

CREATE TABLE BOOKING(
   BOOKING_ID INT PRIMARY KEY AUTO_INCREMENT,
   LEARNER_ID INT NOT NULL,
   TUTOR_ID INT NOT NULL,
   SKILL_ID INT NOT NULL,
   SESSION_DATE DATE NOT NULL,
   START_TIME TIME NOT NULL,
   DURATION DECIMAL(4,2) NOT NULL,
   STATUS VARCHAR(20) DEFAULT 'PENDING',
   
   FOREIGN KEY (LEARNER_ID)
     REFERENCES STUDENT(STUDENT_ID),
     
   FOREIGN KEY (TUTOR_ID)
      REFERENCES STUDENT(STUDENT_ID),
      
   FOREIGN KEY (SKILL_ID)
      REFERENCES SKILL(SKILL_ID),
   CHECK (STATUS IN ('PENDING', 'CONFIRMED','COMPLETED','CANCELLED', 'DISPUTED'))
   );
ALTER TABLE BOOKING
ADD CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP;

SELECT * FROM BOOKING;
   DESC BOOKING;
   
   CREATE TABLE CREDIT_TRANSACTION (
    TRANSACTION_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOKING_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    TRANSACTION_TYPE VARCHAR(30) NOT NULL,
    AMOUNT DECIMAL(5,2) NOT NULL,
    TRANSACTION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID),

    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CHECK (TRANSACTION_TYPE IN ('ESCROW_LOCK', 'ESCROW_RELEASE', 'REFUND'))
);

DESC CREDIT_TRANSACTION;

CREATE TABLE REVIEW (
    REVIEW_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOKING_ID INT NOT NULL,
    REVIEWER_ID INT NOT NULL,
    TUTOR_ID INT NOT NULL,
    RATING DECIMAL(2,1) NOT NULL,
    COMMENT VARCHAR(500),
    REVIEW_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID),

    FOREIGN KEY (REVIEWER_ID)
        REFERENCES STUDENT(STUDENT_ID),

    FOREIGN KEY (TUTOR_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CHECK (RATING BETWEEN 1 AND 5)
);
DESC REVIEW;

CREATE TABLE DISPUTE (
    DISPUTE_ID INT PRIMARY KEY AUTO_INCREMENT,
    BOOKING_ID INT NOT NULL,
    STUDENT_ID INT NOT NULL,
    REASON VARCHAR(500) NOT NULL,
    STATUS VARCHAR(20) DEFAULT 'OPEN',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (BOOKING_ID)
        REFERENCES BOOKING(BOOKING_ID),

    FOREIGN KEY (STUDENT_ID)
        REFERENCES STUDENT(STUDENT_ID),

    CHECK (STATUS IN ('OPEN', 'RESOLVED', 'REJECTED'))
);
DESC DISPUTE;


 
SELECT STUDENT.NAME, SKILL.SKILL_NAME, STUDENT_SKILL.SKILL_TYPE
FROM STUDENT
JOIN STUDENT_SKILL
ON STUDENT.STUDENT_ID = STUDENT_SKILL.STUDENT_ID
JOIN SKILL
ON STUDENT_SKILL.SKILL_ID = SKILL.SKILL_ID;

SELECT
    BOOKING.BOOKING_ID,
    LEARNER.NAME AS LEARNER_NAME,
    TUTOR.NAME AS TUTOR_NAME,
    SKILL.SKILL_NAME,
    BOOKING.SESSION_DATE,
    BOOKING.STATUS
FROM BOOKING
JOIN STUDENT AS LEARNER
ON BOOKING.LEARNER_ID = LEARNER.STUDENT_ID
JOIN STUDENT AS TUTOR
ON BOOKING.TUTOR_ID = TUTOR.STUDENT_ID
JOIN SKILL
ON BOOKING.SKILL_ID = SKILL.SKILL_ID;

SELECT
    CREDIT_TRANSACTION.TRANSACTION_ID,
    STUDENT.NAME,
    CREDIT_TRANSACTION.TRANSACTION_TYPE,
    CREDIT_TRANSACTION.AMOUNT,
    CREDIT_TRANSACTION.BOOKING_ID
FROM CREDIT_TRANSACTION
JOIN STUDENT
ON CREDIT_TRANSACTION.STUDENT_ID = STUDENT.STUDENT_ID;

SELECT 
    STUDENT.NAME,
    COUNT(STUDENT_SKILL.SKILL_ID) AS TOTAL_SKILLS
FROM STUDENT
JOIN STUDENT_SKILL
ON STUDENT.STUDENT_ID = STUDENT_SKILL.STUDENT_ID
GROUP BY STUDENT.NAME;
    
SELECT STUDENT.NAME
FROM STUDENT
WHERE STUDENT.STUDENT_ID IN
(
    SELECT STUDENT_SKILL.STUDENT_ID
    FROM STUDENT_SKILL
    WHERE STUDENT_SKILL.SKILL_ID =
    (
        SELECT SKILL.SKILL_ID
        FROM SKILL
        WHERE SKILL.SKILL_NAME = 'PYTHON'
    )
    AND STUDENT_SKILL.SKILL_TYPE = 'OFFERED'
);

SELECT STUDENT.NAME
FROM STUDENT
WHERE STUDENT.STUDENT_ID IN
(
    SELECT STUDENT_SKILL.STUDENT_ID
    FROM STUDENT_SKILL
    WHERE STUDENT_SKILL.SKILL_ID =
    (
        SELECT SKILL.SKILL_ID
        FROM SKILL
        WHERE SKILL.SKILL_NAME = 'PYTHON'
    )
    AND STUDENT_SKILL.SKILL_TYPE = 'OFFERED'
);

SELECT STUDENT.NAME, COUNT(STUDENT_SKILL.SKILL_ID) AS TOTAL_SKILLS
FROM STUDENT
JOIN STUDENT_SKILL
ON STUDENT.STUDENT_ID = STUDENT_SKILL.STUDENT_ID
GROUP BY STUDENT.NAME;

SELECT STUDENT.NAME, COUNT(STUDENT_SKILL.SKILL_ID) AS TOTAL_SKILLS
FROM STUDENT
JOIN STUDENT_SKILL
ON STUDENT.STUDENT_ID = STUDENT_SKILL.STUDENT_ID
GROUP BY STUDENT.NAME
HAVING COUNT(STUDENT_SKILL.SKILL_ID) > 1;

SELECT STUDENT.STUDENT_ID,
       STUDENT.NAME,
       STUDENT.CREDIT_BALANCE
FROM STUDENT
ORDER BY STUDENT.CREDIT_BALANCE DESC;

SELECT 
    REVIEW.REVIEW_ID,
    REVIEWER.NAME AS REVIEWER_NAME,
    TUTOR.NAME AS TUTOR_NAME,
    REVIEW.RATING,
    REVIEW.COMMENT
FROM REVIEW
JOIN STUDENT AS REVIEWER
ON REVIEW.REVIEWER_ID = REVIEWER.STUDENT_ID
JOIN STUDENT AS TUTOR
ON REVIEW.TUTOR_ID = TUTOR.STUDENT_ID;

SELECT 
    DISPUTE.DISPUTE_ID,
    STUDENT.NAME,
    DISPUTE.BOOKING_ID,
    DISPUTE.REASON,
    DISPUTE.STATUS
FROM DISPUTE
JOIN STUDENT
ON DISPUTE.STUDENT_ID = STUDENT.STUDENT_ID;

CREATE VIEW OFFERED_SKILLS AS
SELECT 
    STUDENT.STUDENT_ID,
    STUDENT.NAME,
    SKILL.SKILL_NAME,
    SKILL.CATEGORY
FROM STUDENT
JOIN STUDENT_SKILL
ON STUDENT.STUDENT_ID = STUDENT_SKILL.STUDENT_ID
JOIN SKILL
ON STUDENT_SKILL.SKILL_ID = SKILL.SKILL_ID
WHERE STUDENT_SKILL.SKILL_TYPE = 'OFFERED';

SELECT * FROM OFFERED_SKILLS;

select*from student;